spring:
  datasource:
#    url: jdbc:mysql://de-6-2-database-web-temp.ch4xfyi6stod.ap-northeast-2.rds.amazonaws.com:3306/trippers?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://de-6-2-database-web.ch4xfyi6stod.ap-northeast-2.rds.amazonaws.com:3306/trippers?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: trippers
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true